packages:
  - packages/*
  - third-party/common/ts

blockExoticSubdeps: true

catalog:
  '@aws-sdk/client-dynamodb': 3.1045.0
  '@aws-sdk/client-lambda': 3.1045.0
  '@aws-sdk/client-sns': 3.1045.0
  '@aws-sdk/client-ssm': 3.1045.0
  '@aws-sdk/lib-dynamodb': 3.1045.0
  '@eslint/js': 10.0.1
  '@types/aws-lambda': 8.10.161
  '@types/node': 25.7.0
  '@vitest/coverage-v8': 4.1.6
  '@vitest/ui': 4.1.6
  aws-cdk: 2.1121.0
  aws-cdk-lib: 2.253.1
  cdk-lambda-llrt: 0.1.4
  constructs: 10.6.0
  cross-env: 10.1.0
  eslint: 10.3.0
  eslint-plugin-simple-import-sort: 13.0.0
  jiti: 2.7.0
  knip: 6.12.2
  npm-run-all: 4.1.5
  typescript: 6.0.3
  typescript-eslint: 8.59.3
  vitest: 4.1.6

# Delay newly published versions for one day to reduce supply-chain risk.
minimumReleaseAge: 1440

# Use hoisted node linker for compatibility with LlrtFunction construct. This construct bundles
# dependencies using docker, which does not work with host's symlinks.
nodeLinker: hoisted

onlyBuiltDependencies:
  - aws-sdk
  - esbuild

trustPolicy: no-downgrade
